       version: '2'

        networks:
          byfn:
        services:
          ca2:
            image: hyperledger/fabric-ca
            environment:
              - FABRIC_CA_HOME=/etc/hyperledger/fabric-ca-server
              - FABRIC_CA_SERVER_CA_NAME=ca-org3
              - FABRIC_CA_SERVER_TLS_ENABLED=true
              - FABRIC_CA_SERVER_TLS_CERTFILE=/etc/hyperledger/fabric-ca-server-config/ca.org3.example.com-cert.pem
              - FABRIC_CA_SERVER_TLS_KEYFILE=/etc/hyperledger/fabric-ca-server-config/b5f973338e883bdd4cf8346ce40cd431d65fe83bccbbb2771349d9a38f674102_sk
            ports:
              - "9054:7054"
            command: sh -c 'fabric-ca-server start --ca.certfile /etc/hyperledger/fabric-ca-server-config/ca.org3.example.com-cert.pem --    ca.keyfile /etc/hyperledger/fabric-ca-server-config/b5f973338e883bdd4cf8346ce40cd431d65fe83bccbbb2771349d9a38f674102_sk -b admin:adminpw -d'
            volumes:
              - ./org3-artifacts/crypto-config/peerOrganizations/org3.example.com/ca/:/etc/hyperledger/fabric-ca-server-config
            container_name: ca_peerOrg3
            networks:
              - byfn
